services:
- type: web
  name: YoutuBaixa-18mais
  runtime: node
  repo: https://github.com/Sidneiba/YoutuBaixa-
  plan: free
  region: oregon
  buildCommand: npm install
  startCommand: node server.js
  envVars:
    - key: PORT
      value: 10000
  disks:
    - name: uploads
      mountPath: /uploads
      sizeGB: 1
version: "1"
